name: Build and Publish
on:
  pull_request:
    types: [closed]


jobs: 
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm install vsce
    - run: vsce package
      # args: publish -p $PUBLISHER_TOKEN
      